### ISSUE TITLE
Migrate bookmarklets in toolbox to functions

### ISSUE THREAD

**Issue by gotdibbs** [gotdibbs/Dynamics-CRM-Bookmarklets#20]
Originally bookmarklets were included in the toolbox UI to reduce code, but as bookmarklets are being deprecated, a split out is warranted for better debugging. Bookmarklets have a finite function length so removing that limitation will help us make newer better experiences.

**Comment by Nafferty** [comment]
@gotdibbs Missing CRM dev? Glad to see there's still activity here. It's almost like you're not gone :(

**Comment by gotdibbs** [comment]
@Nafferty I wouldn't say I'm exactly missing it but I'm not not missing it. Just trying to keep all my friends (read: weekly users) in the Netherlands happy 😅 

![image](https://user-images.githubusercontent.com/1540648/72938790-2c0d9180-3d31-11ea-951e-447c06729834.png)
