### ISSUE TITLE
Toggle Schema names does not stay on.

### ISSUE THREAD

**Issue by ChrisAdamsUK** [gotdibbs/Dynamics-CRM-Bookmarklets#44]
## What is the current behavior? How do you reproduce it?
Toggle Schema Names is always on, clicking the toggle button briefly removes them then they show again.

## What is the expected behavior?
Clicking the toggle button should switch off the schema names then clicking again should show them.

## Please tell us about your environment:

  - Dynamics Version: 9.1.0000.26437

  - Browser: Edge 86.0.622.69 (Official build) (64-bit)

  - Toolbox Version: `2.3.1`

## Other information
> For example: screenshots, detailed explanations, stacktraces, related issues, suggestions how to fix, links for us to have context, etc.

![image](https://user-images.githubusercontent.com/37700023/103644887-05029c80-4f4f-11eb-95ee-83275f1ed6d2.png)

![image](https://user-images.githubusercontent.com/37700023/103644929-18ae0300-4f4f-11eb-9f49-010120388d5c.png)

**Comment by gotdibbs** [comment]
Thanks for the heads up, I will take a look and see if I can figure out what is up.

**Comment by gotdibbs** [comment]
Hey @ChrisAdamsUK I took a look at this just now and I'm not able to reproduce in version of Dynamics 365 that I have access to (`9.1.0000.25851`). I am on the latest version of Edge though which appears to be newer than what you indicated.

Would it be possible for you to update your browser or try Chrome to confirm if the behavior persists in either of those scenarios? And could you confirm this happens on multiple entities, not just the `jfsc_pq` one in your screenshot?

I will give this a few days to see if my Dynamics environment gets updated, but the code here is relatively simple so it is either something unique to your environment or an update issue. If it's the latter, you could help debug the issue in your environment and make a pull request, or we'll just have to wait for my environment to get updated.

**Comment by ChrisAdamsUK** [comment]
Hi William,

I have installed it on Edge my personal machine and it works fine (v87). The machine I am having issues with is my works machine which is running v86. I cannot try it on Chrome on there as there is a corporate block on Chrome Extensions (they haven't got round to blocking Edge ones yet). I will try to find time to investigate further, but I would put it on the back burner for now if it is only affecting older versions of Edge.

Regards
Chris

**Comment by ChrisAdamsUK** [comment]
Hi William,

I’ve further investigated this and the issue is that I had the Dynamics Metadata browser extension added also. In this I had the show schema label name set (I didn’t even know I had set it), this was the label that was staying on screen, not the GotDibbs one 😊

Apologies for wasting your time. ☹

I will give good feedback as currently this is the only Edge extension for Dynamics and is better than Power Pane or Level Up.

Regards
Chris

**Comment by gotdibbs** [comment]
Ah that's an interesting collision. I may look into that extension and see if there's anything I can do to prevent a collision.

Thanks so much for your review and for your help troubleshooting!
